//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnCNNB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Baochisonuoc
    {
        public int ID { get; set; }
        public string NGUOIBAOCHISO { get; set; }
        public string DANHBO { get; set; }
        public string DIENTHOAI { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> CHISONUOC { get; set; }
        public string TENHOPDONG { get; set; }
        public string DIACHI1 { get; set; }
        public string DIACHI2 { get; set; }
        public string QUAN { get; set; }
        public string PHUONG { get; set; }
        public Nullable<System.DateTime> NGAYBAO { get; set; }
    }
}
