//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnCNNB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giaytocanthiet
    {
        public Giaytocanthiet()
        {
            this.LoaiFrom_GiayTo = new HashSet<LoaiFrom_GiayTo>();
        }
    
        public int ID { get; set; }
        public string TenGiayTo { get; set; }
        public string LOAI { get; set; }
        public Nullable<bool> APDUNG { get; set; }
    
        public virtual ICollection<LoaiFrom_GiayTo> LoaiFrom_GiayTo { get; set; }
    }
}
