//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnCNNB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiFrom_GiayTo
    {
        public int ID { get; set; }
        public Nullable<int> ID_GiayTo { get; set; }
        public Nullable<int> ID_LoaiFrom { get; set; }
        public Nullable<int> TrangThai { get; set; }
    
        public virtual Giaytocanthiet Giaytocanthiet { get; set; }
        public virtual tbGanmoi tbGanmoi { get; set; }
    }
}
