//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnCNNB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBaiViet
    {
        public int ID_BaiViet { get; set; }
        public Nullable<int> ID_ChuyenMuc { get; set; }
        public string TieuDe { get; set; }
        public string MoTa { get; set; }
        public string HinhDaiDien1 { get; set; }
        public string HinhDaiDien2 { get; set; }
        public string NoiDung { get; set; }
        public string Video { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<int> TinNoiBat { get; set; }
        public Nullable<int> TinHot { get; set; }
        public string Nguoidang { get; set; }
        public string Nguoiduyet { get; set; }
        public Nullable<System.DateTime> Ngayduyet { get; set; }
        public string Ghichu { get; set; }
    
        public virtual tbChuyenMucBaiViet tbChuyenMucBaiViet { get; set; }
    }
}
