//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnCNNB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDiemthutien
    {
        public int ID { get; set; }
        public string TENDD { get; set; }
        public string MOTA { get; set; }
        public string MAPHUONG { get; set; }
        public string MAQUAN { get; set; }
        public string DIACHI { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Time { get; set; }
        public System.Data.Spatial.DbGeography LOCATION { get; set; }
    }
}
