//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnCNNB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDieuchinh
    {
        public tbDieuchinh()
        {
            this.tbHokhaus = new HashSet<tbHokhau>();
        }
    
        public int ID { get; set; }
        public string MADB { get; set; }
        public string SOBN { get; set; }
        public int LOAIDC { get; set; }
        public string NGUOINHAP { get; set; }
        public System.DateTime NGAYNHAP { get; set; }
        public string GHICHU { get; set; }
        public string KYHIEULUC { get; set; }
        public Nullable<System.DateTime> NGAYHH { get; set; }
        public string DOT { get; set; }
        public string MAHD { get; set; }
        public string MST { get; set; }
        public Nullable<int> DINHMUC { get; set; }
        public Nullable<int> GIABIEU { get; set; }
        public string HOTEN { get; set; }
        public string DIACHI1 { get; set; }
        public string DIACHI2 { get; set; }
        public string MAPHUONG { get; set; }
        public string MAQUAN { get; set; }
        public string SODT { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> NGAYLD { get; set; }
        public Nullable<int> TONGNK { get; set; }
        public Nullable<int> SONK { get; set; }
        public string CODH { get; set; }
        public string MAQP { get; set; }
        public string MAHDDC { get; set; }
        public string MSTDC { get; set; }
        public Nullable<int> DINHMUCDC { get; set; }
        public Nullable<int> TONGNKDC { get; set; }
        public Nullable<int> SONKDC { get; set; }
        public Nullable<int> GIABIEUDC { get; set; }
        public string HOTENDC { get; set; }
        public string DIACHI1DC { get; set; }
        public string DIACHI2DC { get; set; }
        public string MAPHUONGDC { get; set; }
        public string MAQUANDC { get; set; }
        public string SODTDC { get; set; }
        public string EMAILDC { get; set; }
        public string CODHDC { get; set; }
        public string MAQPDC { get; set; }
        public string GIAYTO { get; set; }
    
        public virtual ICollection<tbHokhau> tbHokhaus { get; set; }
    }
}
