//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnCNNB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbGanmoi
    {
        public tbGanmoi()
        {
            this.LoaiFrom_GiayTo = new HashSet<LoaiFrom_GiayTo>();
        }
    
        public int ID { get; set; }
        public string SOHS { get; set; }
        public string LOAIYEUCAU { get; set; }
        public string TENKH { get; set; }
        public string DIACHI1 { get; set; }
        public string DIACHI2 { get; set; }
        public string MAQUAN { get; set; }
        public string MAPHUONG { get; set; }
        public string EMAIL { get; set; }
        public string DIENTHOAI { get; set; }
        public string TENHD { get; set; }
        public string MDSD { get; set; }
        public string EMAILBC { get; set; }
        public string GHICHU { get; set; }
        public System.Data.Spatial.DbGeography TOADO { get; set; }
        public Nullable<System.DateTime> NGAYYC { get; set; }
        public Nullable<int> TRANGTHAI { get; set; }
        public string DANHBO { get; set; }
        public Nullable<int> ID_YEUCAUNANGDOI { get; set; }
    
        public virtual MUCLUCYEUCAUNANGDOI MUCLUCYEUCAUNANGDOI { get; set; }
        public virtual ICollection<LoaiFrom_GiayTo> LoaiFrom_GiayTo { get; set; }
        public virtual tbLoaiQuitrinh tbLoaiQuitrinh { get; set; }
        public virtual tbLoaiQuitrinh tbLoaiQuitrinh1 { get; set; }
    }
}
