//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnCNNB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHokhau
    {
        public int ID { get; set; }
        public string MADB { get; set; }
        public Nullable<int> LOAIKH { get; set; }
        public string SOHK { get; set; }
        public string LOAIGT { get; set; }
        public Nullable<System.DateTime> NGAYCAP { get; set; }
        public string HOTEN { get; set; }
        public string DIACHI { get; set; }
        public Nullable<int> TONGNK { get; set; }
        public Nullable<int> SONK { get; set; }
        public Nullable<int> LOAIDM { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public Nullable<System.DateTime> NGAYKT { get; set; }
        public Nullable<int> NHAP { get; set; }
        public string GHICHU { get; set; }
        public Nullable<int> DIEUCHINH { get; set; }
        public int TRANGTHAI { get; set; }
    
        public virtual tbDieuchinh tbDieuchinh { get; set; }
    }
}
