//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnCNNB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbHoidap
    {
        public int ID { get; set; }
        public string MaDB { get; set; }
        public string Hoten { get; set; }
        public string Diachi { get; set; }
        public Nullable<int> Dienthoai { get; set; }
        public string Email { get; set; }
        public string Noidunghoidap { get; set; }
        public Nullable<System.DateTime> Ngayguicauhoi { get; set; }
        public Nullable<double> Trangthaicauhoi { get; set; }
        public string Noidungtraloi { get; set; }
        public string Nguoitraloi { get; set; }
        public Nullable<System.DateTime> Ngaytraloi { get; set; }
    }
}
