//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnCNNB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLichcup
    {
        public int ID { get; set; }
        public string DANHBO { get; set; }
        public string KY { get; set; }
        public string DOT { get; set; }
        public string NAM { get; set; }
        public Nullable<System.DateTime> NGAYBD { get; set; }
        public Nullable<System.DateTime> NGAYKT { get; set; }
        public string LYDO { get; set; }
        public string KHUVUC { get; set; }
        public string GHICHU { get; set; }
        public string NHANVIENDS { get; set; }
        public string PHONENV { get; set; }
    }
}
