//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnCNNB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLoaiQuitrinh
    {
        public tbLoaiQuitrinh()
        {
            this.tbGanmois = new HashSet<tbGanmoi>();
            this.tbGanmois1 = new HashSet<tbGanmoi>();
            this.tbXulyyeucaus = new HashSet<tbXulyyeucau>();
        }
    
        public string MALOAI { get; set; }
        public string TENLOAI { get; set; }
        public Nullable<bool> THUPHI { get; set; }
        public Nullable<int> SONGAY { get; set; }
    
        public virtual ICollection<tbGanmoi> tbGanmois { get; set; }
        public virtual ICollection<tbGanmoi> tbGanmois1 { get; set; }
        public virtual ICollection<tbXulyyeucau> tbXulyyeucaus { get; set; }
    }
}
