//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnCNNB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMadanhbo
    {
        public int ID { get; set; }
        public string MADB { get; set; }
        public string TENKH { get; set; }
        public string EMAIL { get; set; }
        public string SODT { get; set; }
        public string DIACHI1 { get; set; }
        public string DIACHI2 { get; set; }
        public string MAPHUONG { get; set; }
        public string MAQUAN { get; set; }
        public string MSTHUE { get; set; }
        public Nullable<byte> CULY { get; set; }
        public Nullable<int> DINHMUC { get; set; }
        public Nullable<int> TONGNK { get; set; }
        public Nullable<int> SONK { get; set; }
        public Nullable<int> GIABIEU { get; set; }
        public Nullable<double> TLSH { get; set; }
        public Nullable<double> TLHC { get; set; }
        public Nullable<double> TLSX { get; set; }
        public Nullable<double> TLDV { get; set; }
    }
}
