//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnCNNB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPhuong
    {
        public string MAPHUONG { get; set; }
        public string MAQUAN { get; set; }
        public string TENPHUONG { get; set; }
        public string MAQP { get; set; }
        public string DOT { get; set; }
        public string GHICHU { get; set; }
    }
}
