//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnCNNB_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTiennuoc
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> NGAYHD { get; set; }
        public string MADB { get; set; }
        public string KY { get; set; }
        public string DOT { get; set; }
        public string NAM { get; set; }
        public Nullable<System.DateTime> TUNGAY { get; set; }
        public Nullable<System.DateTime> DENNGAY { get; set; }
        public Nullable<int> CSCU { get; set; }
        public Nullable<int> CSMOI { get; set; }
        public Nullable<int> TIEUTHU { get; set; }
        public Nullable<decimal> TIENNUOC { get; set; }
        public Nullable<decimal> PHIBVMT { get; set; }
        public Nullable<decimal> THUEVAT { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public string GHICHU { get; set; }
        public Nullable<int> TRANGTHAI { get; set; }
    }
}
